version: "3.9"

services:
  indexer:
    command:
      - "--config=/app/agate-config.yaml"
      - "indexer"
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      database:
        condition: service_healthy
    networks:
      - agate-net
    volumes:
      - ./agate-config-docker.yaml:/app/agate-config.yaml
    stop_grace_period: "10m"

  database:
    hostname: database
    image: bitnami/postgresql:15.2.0
    ports:
      - "${AGATE_INDEXER_DATABASE_PORT}:5432"
    environment:
      - POSTGRES_USER=${AGATE_INDEXER_DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${AGATE_INDEXER_DATABASE_PASSWORD}
      - POSTGRES_DATABASE=${AGATE_INDEXER_DATABASE_DBNAME}
    networks:
      - agate-net
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${AGATE_INDEXER_DATABASE_DBNAME}", "-U", "${AGATE_INDEXER_DATABASE_USERNAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - indexer-data:/var/lib/postgresql/data
    stop_grace_period: "10m"

volumes:
  indexer-data:

networks:
  agate-net:
